version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fintech-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fintech
      MYSQL_USER: fintech_user
      MYSQL_PASSWORD: fintech_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
